### ISSUE TITLE
`Vue is not defined`

### ISSUE THREAD

**Issue by DanHulton** [grid-js/gridjs-vue#427] opened 2021-11-28 01:55 UTC
**Describe the bug**
Following the documentation exactly produces this error in the console.

**To Reproduce**
1. Go to https://gridjs.io/docs/integrations/vue/
2. Follow the documentation
3. Attempt to load page.
4. Console instead shows error `ReferenceError: Vue is not defined`.

**Expected behavior**
Grid should display without error.

**Desktop (please complete the following information):**
 - OS: Mac OS 12.0.1
 - Browser: Firefox
 - Version: 94.0.1

**Additional context**

I am using Vue 3, but others have reported this same issue using Vue 2, here: https://github.com/grid-js/gridjs-vue/issues/426

It was staled when it really should not have been, as the issue is still active and a complete blocker.

**Comment by dombavetta** [comment] 2021-11-29 01:13
Having the same issue with Vue 2.

**Comment by Dev314** [comment] 2021-11-29 23:07
I faced the same issue, can't use gridjs-vue 5+. Have to downgrade it to version 4, hope it will be fixed soon.

**Comment by Dev314** [comment] 2021-12-28 17:42
Is it resolved?

**Comment by missingno-io** [comment] 2021-12-29 21:14
I think it's due to how modules are handled now... I ran into this issue and was able to resolve by adding Vue to the window.  I'd say this only a work around but hopefully it helps someone.  
```javascript
import Vue from 'vue';
window.Vue = Vue;
```

**Comment by deviarte** [comment] 2022-01-08 17:00
Same issue for me. No way to get it to work. Downgrade to v4 worked.

**Comment by JowJoris** [comment] 2022-01-26 12:34
How do I fix this for Nuxt3? I can't downgrade to v4 because of dependencies on vue3

**Comment by Grzyb9k** [comment] 2022-01-31 22:34
i have same issue

**Comment by heavyhelli** [comment] 2022-02-15 10:23
I have the same issue in my new Vue3 application.
`main.esm.js?a234:1 Uncaught ReferenceError: Vue is not defined
    at Module.eval (main.esm.js?a234:1:1)
    at eval (main.esm.js:8:30)
    at Module../node_modules/gridjs-vue/dist/main.esm.js (chunk-vendors.js:2659:1)
    at __webpack_require__ (index.js:854:30)
    at fn (index.js:151:20)
    at eval (cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader-v16/dist/index.js?!./src/views/Home.vue?vue&type=script&lang=js:6:68)
    at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader-v16/dist/index.js?!./src/views/Home.vue?vue&type=script&lang=js (index.js:1031:1)
    at __webpack_require__ (index.js:854:30)
    at fn (index.js:151:20)
    at eval (Home.vue?026b:1:1)`

**Comment by JowJoris** [comment] 2022-02-17 12:46
@selfagency Any ideas how to fix this?

**Comment by bbjansen** [comment] 2022-02-17 17:21
have the same issue. downgrading to 4 solves it, but results in many missing features.

**Comment by fbmfbm** [comment] 2022-02-18 09:06
Sam issue for now with VueJS 3 !
Waiting for a fix to  switch to production with GridJs !!
Any one ?

**Comment by ZachVogt** [comment] 2022-02-23 15:09
Same story here, can't even get the [base example](https://gridjs.io/docs/integrations/vue) code to work.  Any updates on this?

**Comment by kaanrkaan** [comment] 2022-03-27 20:23
@selfagency Are you there ?

**Comment by therealokoro** [comment] 2022-04-22 13:34
We really need a fix to this issue. Pleas someone heeelp

**Comment by palanza** [comment] 2022-04-28 13:17
+1

**Comment by LeaderbotX400** [comment] 2022-05-12 23:21
+1

**Comment by KayahanKahriman** [comment] 2022-05-13 07:41
Same here

**Comment by aphavichitr** [comment] 2022-05-13 23:33
+1

**Comment by aphavichitr** [comment] 2022-05-16 21:05
> I think it's due to how modules are handled now... I ran into this issue and was able to resolve by adding Vue to the window. I'd say this only a work around but hopefully it helps someone.
> 
> ```js
> import Vue from 'vue';
> window.Vue = Vue;
> ```

@missingno-io Where did you add this? I tried adding it and it still wasn't resolving.

**Comment by aphavichitr** [comment] 2022-05-16 23:09
I think the issue is this library isn't supporting Vue 3, I found this thread with a fork for Vue 3 compatibility, but I've decided to use the Vanilla JS implementation.

https://github.com/grid-js/gridjs-vue/issues/312#issuecomment-911820153

**Comment by AbakusToTheMoon** [comment] 2022-06-21 14:00
Hi everyone,

I'am trying to use GridJS with vue3 but as I see the problem is still not fixed, do someone has an idea to fix it ?

**Comment by therealokoro** [comment] 2022-06-21 15:51
I was able to use gridjs with vue, but this was with the gridjs core library and not the wrapper for vue i.e gridjs-vue.

Here is how i used it
```vue
<script setup lang="ts">
	import { Grid } from "gridjs"
	import "gridjs/dist/theme/mermaid.css"

       // create a ref to hold the table in template
	const myTable = ref()
        // create a ref variable to hold new gridjs instance
	const gridjs = ref()

	onMounted(() => {
		gridjs.value = new Grid({
			columns: ["Name", "Email", "Phone Number"],
			data: [
				["John", "john@example.com", "(353) 01 222 3333"],
				["Mark", "mark@gmail.com", "(01) 22 888 4444"],
				["Eoin", "eoin@gmail.com", "0097 22 654 00033"],
				["Sarah", "sarahcdd@gmail.com", "+322 876 1233"],
				["Afshin", "afshin@mail.com", "(353) 22 87 8356"]
			],
			pagination: true,
			search: true,
			sort: true
		})

		gridjs.value.render(myTable.value)
		gridjs.value.on("cellClick", (...args: any) => console.log(args))
	})
</script>

<template>
	<h3 class="text-lg font-semibold">Gridjs Table</h3>
	<div id="id" ref="myTable"></div>
</template>

<style></style>

```

**Closed as completed** 2022-09-20 18:39 UTC
Labels: wontfix

**Comment by tuanhaviet22** [comment] 2023-02-07 07:08
Still face this error

**Comment by vitalibr** [comment] 2023-03-19 19:00
still facing this error...

**Comment by XAldrikX** [comment] 2023-07-19 21:24
Same error for me...

**Comment by randomComitter** [comment] 2023-08-07 12:11
Also have the same issue with vue 3.2.45 and gridjs-vue 5.0.4
